cmake_minimum_required(VERSION 3.13)

macro(setupCrossCompiler )
    # specify the cross compiler
    SET(GCC_PATH /home/andrew/tools/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/)
    SET(CMAKE_C_COMPILER_WORKS 1)
    SET(CMAKE_C_COMPILER_WORKS 1)
    SET(CMAKE_C_COMPILER ${GCC_PATH}arm-none-eabi-gcc)
    SET(CMAKE_CXX_COMPILER_WORKS 1)
    SET(CMAKE_CXX_COMPILER ${GCC_PATH}arm-none-eabi-g++)
    SET(CMAKE_ASM_COMPILER ${GCC_PATH}arm-none-eabi-as)
    set(AS ${GCC_PATH}arm-none-eabi-as)
    set(AR ${GCC_PATH}arm-none-eabi-ar)
    set(OBJCOPY ${GCC_PATH}arm-none-eabi-objcopy)
    set(OBJDUMP ${GCC_PATH}arm-none-eabi-objdump)
    set(SIZE ${GCC_PATH}arm-none-eabi-size)
endmacro()

macro(setStandardFlagsForCrossCompiler debugLevel codeOptimization )
    SET(DEBUG_LEVEL ${debugLevel})
    SET(DEFAULT_CODE_OPTIMIZATION ${codeOptimization} )
    SET(DEFAULT_CODE_OPTIMIZATION "${DEFAULT_CODE_OPTIMIZATION} -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fsingle-precision-constant -fmessage-length=0 -flto")
    SET(DEFAULT_CXX_OPTIMIZATION "-fno-exceptions -fno-rtti -fno-use-cxa-atexit -fno-threadsafe-statics -fabi-version=6")
    SET(WARNINGS "-pedantic -pedantic-errors -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wfloat-equal -Werror -Wno-unknown-pragmas ")
    SET(CXX_WARNINGS "-Wctor-dtor-privacy -Wnon-virtual-dtor -Wstrict-null-sentinel -Wsign-promo -Weffc++ ")
    SET(LINKER_MISC " --specs=nano.specs --specs=nosys.specs ")
    SET(LINKER_GENERAL "  -nostartfiles -Xlinker --gc-sections ")
endmacro()