cmake_minimum_required(VERSION 3.13)
function(add_module srcDirectory moduleName)
  if( NOT ARGN )
    add_library(${moduleName} OBJECT )
    add_library(mod::${moduleName} ALIAS ${moduleName})
    add_subdirectory( ${srcDirectory} )
    message(STATUS "Adding default Module: ${moduleName}")
  else ()
    add_library(${moduleName} OBJECT )
    add_library(mod::${moduleName} ALIAS ${moduleName})
    add_subdirectory( ${srcDirectory} ${ARGN})
    message(STATUS "Adding external Module: ${ARGN}")
  endif()
endfunction()
