cmake_minimum_required(VERSION 3.15)
function(add_module directory moduleName )
  if( NOT ARGN )
    add_library(${moduleName} OBJECT "")
    add_subdirectory( ${directory})
    message(STATUS "Adding default Module: ${moduleName}")
  else ()
    message(STATUS "Module not found: ${moduleName}")
  endif()
endfunction()