cmake_minimum_required(VERSION 3.13)

macro(setupUnitTestCompiler )
    # specify the cross compiler
    SET(CMAKE_C_COMPILER_WORKS 1)
    SET(CMAKE_C_COMPILER gcc)
    SET(CMAKE_CXX_COMPILER_WORKS 1)
    SET(CMAKE_CXX_COMPILER g++)
    SET(CMAKE_ASM_COMPILER gcc)
    set(AS as)
    set(AR ar)
    set(OBJCOPY ojcopy)
    set(OBJDUMP objdump)
    set(SIZE size)
endmacro()

macro(setStandardFlagsForUnitTest debugLevel codeOptimization )
    SET(DEBUG_LEVEL ${debugLevel})
    SET(DEFAULT_CODE_OPTIMIZATION ${codeOptimization}  )
    SET(DEFAULT_CODE_OPTIMIZATION "${DEFAULT_CODE_OPTIMIZATION} -fno-inline -fno-inline-small-functions -fno-default-inline --coverage -fprofile-arcs -fno-exceptions -fsigned-char -fsingle-precision-constant -fmessage-length=0 -flto  -fno-inline" )
    SET(WARNINGS "-pedantic -pedantic-errors -Wunused -Wuninitialized -Wall -Wextra  -Wconversion -Wpointer-arith -Wshadow -Wfloat-equal -Werror -Wno-unknown-pragmas ")
    SET(CXX_WARNINGS "-Wctor-dtor-privacy -Wnon-virtual-dtor -Wstrict-null-sentinel -Wsign-promo -Weffc++ ")
    add_definitions(-DUNIT_TESTS=1)

endmacro()